[wokwi]
version = 1
elf = ".pio/build/debug/WaterChamber-ca19c4a3222886401da1e7c260c5b989c3da3094-debug-ca19c4a-master.elf"
firmware = ".pio/build/debug/WaterChamber-ca19c4a3222886401da1e7c260c5b989c3da3094-debug-ca19c4a-master.bin"

[[net.forward]]
from = "localhost:8180"
to = "target:80"